#!/bin/sh

case "$1" in
   -doc* ) echo "print_graph [foo.in foo.out]"
           echo "for more details execute" \
	        "\`hpcm_display_graph -doc | less'"
           exit 1;;
    "" ) in=relativeneighbor.in
         out=relativeneighbor.out;;
    *  ) in="$1"
         out="$2";;
esac

case "$out" in
    "" ) echo "print_graph [foo.in foo.out]"
         echo "wrong number of arguments"
         exit 1;;
esac

user=`id -un`

hpcm_display_graph -ps "$in" "$out" \
    | printer_pipe "$user" "$out"
